package se.alipsa.games.sc.io

enum LoadErrorCode {
  MISSING_REQUIRED_FIELD,
  INVALID_TRACK_ID,
  INVALID_DIMENSIONS,
  INVALID_SPAWN_WEIGHTS,
  INVALID_SPECIAL_PIECES,
  INVALID_SCORING_RULES,
  INVALID_BLOCKERS,
  INVALID_OBJECTIVES,
  INVALID_BOARD_GEOMETRY,
  MALFORMED_JSON,
  DUPLICATE_TRACK_ID,
  UNKNOWN_CANDY_TYPE,
  NO_TRACKS_FOUND
}
